### ISSUE TITLE
Pointing-Relationen werden weiterhin nicht bzw. falsch exportiert

### ISSUE THREAD

**Issue by Annotation-123** [infraling/atomic#35]
In Atomic 0.1.9 werden jetzt zwar SPAN und STRUCT nach RelANNIS exportiert. Die Pointing-Relationen werden aber (von struct-Knoten zu Token oder zwischen zwei Span-Knoten) nicht übertragen.

Ich kann lediglich erkennen, dass beim PAULA-Export folgender Fehler nach wie vor besteht, der dann auch bei der Konvertierung mit SnP angegeben wird: Eine pointing-Relation von einem Strukturknoten zu einem Token wird so angegeben:

[Spitze Klammer] rel id="sPointingRel2" xlink:href="null#structure1" target="nolayer.corpus_document.tok.xml#sTok13"/>

hinter "xlink:href="" müsste der Dateinanem erscheinen, und nicht null stehen.

Pointing-Relationen zwischen Span-Annotationen -also zwischen zwei Einheiten, die aus mehr als einem Token bestehen, werden gar nicht expoertiert.

Beste Grüße

**Comment by sdruskat** [comment]
Ist das Problem bereits gelöst?

**Comment by sdruskat** [comment]
Habe das nochmal überprüft.

> "In Atomic 0.1.9 werden jetzt zwar SPAN und STRUCT nach RelANNIS exportiert. Die Pointing-Relationen werden aber (von struct-Knoten zu Token oder zwischen zwei Span-Knoten) nicht übertragen."

Habe dazu ein Projekt angelegt und die entsprechende Struktur minimal nachgebaut:

![pointingrels](https://cloud.githubusercontent.com/assets/3007126/5891963/5c0f3ce6-a4af-11e4-8756-25d9721f9f7a.png)

Beim Export zu relANNIS 3.2 bekomme ich in "component.tab" auch die entsprechenden Pointing Relations angezeigt:

    13	p	default_ns	span_to_span_pointingrel
    14	p	default_ns	struct_to_token_pointingrel

D.h., die Kanten sind da. Werden sie in ANNIS nicht angezeigt?

> Ich kann lediglich erkennen, dass beim PAULA-Export folgender Fehler nach wie vor besteht, der dann auch bei der Konvertierung mit SnP angegeben wird: Eine pointing-Relation von einem Strukturknoten zu einem Token wird so angegeben:

>`<rel id="sPointingRel2" xlink:href="null#structure1" target="nolayer.corpus_document.tok.xml#sTok13"/>`

> hinter "xlink:href="" müsste der Dateinanem erscheinen, und nicht null stehen.

> Pointing-Relationen zwischen Span-Annotationen -also zwischen zwei Einheiten, die aus mehr als einem Token bestehen, werden gar nicht expoertiert.

Den ersten Fehler (`xlink:href="null#structure1"`) kann ich bestätigen. Vielleicht kann @FlorianZipser hier helfen? Den zweiten Fehler (Pointing Relationen zwischen Spans werden nicht exportiert) kann ich *nicht* bestätigen. Bei Export zu PAULA 1.0 bekomme ich folgende Dateien.

![paula](https://cloud.githubusercontent.com/assets/3007126/5891989/0de76f0a-a4b1-11e4-84b5-a1fcdce6ffe3.png)

Inhalt der **span_to_span_pointingrel.xml*:

    <?xml version="1.0" standalone="no"?>
    <!DOCTYPE paula SYSTEM "paula_rel.dtd">
    <paula version="1.1">
    	<header paula_id="nolayer.corpus_document.pointRel_span_to_span_pointingrel"/>
    	<relList xmlns:xlink="http://www.w3.org/1999/xlink" type="span_to_span_pointingrel" >
    		<rel id="sPointingRel2" xlink:href="nolayer.corpus_document.mark.xml#sSpan1" target="nolayer.corpus_document.mark.xml#sSpan2"/>
    	</relList>
    </paula>

Die PR taucht auch in der **corpus_document.anno.xml** auf:

    		<struct id="anno_1">
    			<rel id="rel_2" xlink:href="nolayer.corpus_document.pointRel_struct_to_token_pointingrel.xml" />
    			<rel id="rel_3" xlink:href="nolayer.corpus_document.mark.xml" />
    			<rel id="rel_4" xlink:href="nolayer.corpus_document.struct.xml" />
   			<rel id="rel_5" xlink:href="nolayer.corpus_document.tok.xml" />
    			<rel id="rel_6" xlink:href="nolayer.corpus_document.pointRel_span_to_span_pointingrel.xml" />
    		</struct>

**Comment by Annotation-123** [comment]
Ich hatte zuerst den Hinweis mit dem Setzen der Stypes (t:x) nicht gesehen Damit hat es dann funktioniert. Die Realtionen sind in ANNIS abfragbar. DIe Pointing-Relationen von Knoten zu Token innerhalb einer Struktur werden aber nicht visualisiert. Aber das Problem habe ich mit ANNIS schon öfter gehabt. Danke

**Comment by sdruskat** [comment]
Super. Freut mich.
Closing this as FIXED.
