### ISSUE TITLE
Treetagger-Import erzeugt keine Datei und Exmaralda-Import funktioniert nur bei kleinen Korpora

### ISSUE THREAD

**Issue by Annotation-123** [infraling/atomic#39]
TreetaggerImporter erzeugt keine Datei, die sich im graphischen Editor öffnen lässt.

Wenn ich etwas aus Exmaralda importiere, funktioniert das bei einem Satz, aber mein Korpus (1 Text, 3300 token) lässt sich nicht öffenen. ATOMIC reagiert beim Öffnen nach 5 Minuten immer noch nicht.

**Comment by sdruskat** [comment]
Danke für den Report!

Den TreetaggerImporter-Fehler muss ich mir anschauen. Der Lade-Bug wird mit 0.1.10 behoben. Das Problem ist das teure Rendering der Graphen. 0.1.10 bringt auf Satzerkennung basierende Navigation im Editor, so dass nicht immer der komplette Graph gerendert werden muss.

**Comment by Annotation-123** [comment]
Der Fehler des TreeTagger-Imports tritt bei mir auch bei ganz einfachen Beispielen auf:

Ein\tART\ein
Test\tNN\tTest

abgespiecher als TXT (uft-8). Es wird eine Salt-Datei erzeugt, aber der eigentliche Ordner mit dem Korpus fehlt.

Habe ATOMIC jetzt noch mal mit 500 token laufen lassen und nur teilweise SPAN STRUCT annotiert und hier wurde es dann auch mit der Zeit sehr träge - vor allem wenn ich nicht die Konsole, sondern den graphischen Weg genutzt habe.

**Comment by sdruskat** [comment]
Zum TreeTagger-Import: die TreeTagger-Datei muss (s. Dokumentation des Moduls) mit einer der folgenden Endungen abgespeichert werden. 

    .tab
    .tt

> The expected input file encoding defaults to "UTF-8" and is also definable in the properties file. Any input file ́s name is required to end on ".tab" or ".tt".
> [Dokumentation (PDF)](https://korpling.german.hu-berlin.de/p/documents/208)

Beispiel (gespeichert als treetaggertest.tt):

```
I	PP	I
am	VBP	be
testing	VVG	test
the	DT	the
TreeTagger	NP	TreeTagger
import	NN	import
module	NN	module
,	,	,
which	WDT	which
is	VBZ	be
used	VVN	use
in	IN	in
Atomic	NP	Atomic
.	SENT	.
It	PP	it
works	VVZ	work
when	WRB	when
importing	VVG	import
a	DT	a
file	NN	file
with	IN	with
the	DT	the
correct	JJ	correct
file	NN	file
ending	VVG	end
(	(	(
either	DT	either
.tt	NN	.tt
or	CC	or
.tab	NN	.tab
)	)	)
.	SENT	.
```
